# Generated by Django 4.2.5 on 2023-10-06 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_employee_skills_skill_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='date_of_employment',
            field=models.DateField(default=datetime.date(2023, 10, 6)),
        ),
    ]
