# Generated by Django 4.2.5 on 2023-10-01 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_employee_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='QK3591', primary_key=True, serialize=False, unique=True),
        ),
    ]
