# Generated by Django 4.2.5 on 2023-10-01 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_employee_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='employee_id',
        ),
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='XQ3414', primary_key=True, serialize=False, unique=True),
        ),
    ]
