# Generated by Django 4.2.5 on 2023-10-01 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='seniority_rating',
            field=models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], default='beginner', max_length=50),
        ),
    ]
